---
kind: pipeline
type: docker
name: learn-languages

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: learn-languages
      tags:
        - latest
      dry_run: true
  
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      script:
        - cd ~/docker/learn-languages
        - docker-compose restart || docker-compose up -d
      debug: true

trigger:
  branch:
    - main
