---
kind: pipeline
type: docker
name: learn-languages

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
         from_secret: docker_username
      password:
         from_secret: docker_password
      repo: registry.edian-studio.com/learn-languages
      registry: registry.edian-studio.com
      tags:
        - latest
  
  - name: database migrate
    image: node:24-alpine
    environment:
      DATABASE_URL:
        from_secret: database_url
    commands:
      - npm i --no-save prisma@7 @prisma/client@7 "@prisma/adapter-pg"
      - npx prisma migrate deploy

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      script:
        - cd ~/docker/learn-languages
        - docker compose up -d --pull always --force-recreate
      debug: true

trigger:
  branch:
    - main
